name: warzone_companion
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  http: ^0.12.2
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.4
  sqflite: ^1.3.2+1
  path_provider: ^1.6.27
  shared_preferences: ^0.5.12+4
  workmanager: ^0.2.3
  flutter_local_notifications: ^3.0.2
  battery_info: ^1.0.6
  connectivity: ^2.0.2
  awesome_notifications: ^0.0.5+4

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
  - family: Graduate
    fonts:
    - asset: fonts/Graduate-Regular.ttf



  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
